### ISSUE TITLE
The dimenstion generator.settings requests the non-existent parameter "name".

### ISSUE THREAD

**Issue by ChenCMD** [misode/minecraft-schemas#20]
reported from [twitter](https://twitter.com/AiAkaishi/status/1334381438976712704)

**Comment by SPGoding** [comment]
Isn't `name` a thing necessary for inlined settings? I'm not too familiar with worldgen though. :eyes:

**Comment by misode** [comment]
SPGoding is correct. You need to specify `name` when you don't put the noise settings in its own file.

**Comment by ChenCMD** [comment]
So if the noise settings are in that file, I don't think you need a `name`.... am I saying something irrelevant?

**Comment by SPGoding** [comment]
From what I understand, you don't need `name` if the setting is put under `data/<namespace>/worldgen/noise_settings/**.json` because the resource location of it is already provided by its file path. However, you do need a `name` specifying the resource location of this setting if you inlined (i.e. put) it in the dimension file's `settings` field directly.

**Comment by misode** [comment]
Working as intended
